apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: shepherd-role
rules:
- apiGroups: [""]
  resources: ["pods", "nodes"]
  verbs: ["get", "list"]
- apiGroups: ["metrics.k8s.io"]
  resources: ["pods", "nodes"]
  verbs: ["get", "list"]
