apiVersion: apps/v1
kind: Deployment
metadata:
  name: shepherd-deployment
  labels:
    app: shepherd
spec:
  selector:
    matchLabels:
      app: shepherd
  template:
    metadata:
      labels:
        app: shepherd
    spec:
      containers:
      - name: shepherd
        image: ghcr.io/rapour/osrm-dubai-shepherd:v0.1.0
        command: 
        - --locust-url
        - http://locust:8089
