apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: osrm
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://git.launchpad.net/~rapour/rapour/+git/osrm-dubai
    targetRevision: HEAD                              
    path: osrm
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
